steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','hub.docker.com/repository/docker/yusufkaratoprak/hello-world','.']
images:
- 'hub.docker.com/repository/docker/yusufkaratoprak/hello-world'